//     Ooples Finance Stock Indicator Library
//     https://ooples.github.io/OoplesFinance.StockIndicators/
//
//     Copyright © Franklin Moormann, 2020-2022
//     cheatcountry@gmail.com
//
//     This library is free software and it uses the Apache 2.0 license
//     so if you are going to re-use or modify my code then I just ask
//     that you include my copyright info and my contact info in a comment

global using OoplesFinance.StockIndicators.Helpers;

namespace OoplesFinance.StockIndicators.Enums;

public enum IndicatorName
{
    None,
    [Category(IndicatorType.Trend)]
    _1LCLeastSquaresMovingAverage,
    [Category(IndicatorType.Trend)]
    _3HMA,
    [Category(IndicatorType.Momentum)]
    _4MovingAverageConvergenceDivergence,
    [Category(IndicatorType.Momentum)]
    _4PercentagePriceOscillator,
    [Category(IndicatorType.Momentum)]
    AbsolutePriceOscillator,
    [Category(IndicatorType.Momentum)]
    AbsoluteStrengthIndex,
    [Category(IndicatorType.Trend)]
    AbsoluteStrengthMTFIndicator,
    [Category(IndicatorType.Momentum)]
    AcceleratorOscillator,
    [Category(IndicatorType.Volume)]
    AccumulationDistributionLine,
    [Category(IndicatorType.Momentum)]
    AccumulativeSwingIndex,
    [Category(IndicatorType.Trend)]
    AdaptiveAutonomousRecursiveMovingAverage,
    [Category(IndicatorType.Trend)]
    AdaptiveAutonomousRecursiveTrailingStop,
    [Category(IndicatorType.Momentum)]
    AdaptiveErgodicCandlestickOscillator,
    [Category(IndicatorType.Trend)]
    AdaptiveExponentialMovingAverage,
    [Category(IndicatorType.Trend)]
    AdaptiveLeastSquares,
    [Category(IndicatorType.Trend)]
    AdaptiveMovingAverage,
    [Category(IndicatorType.Volatility)]
    AdaptivePriceZoneIndicator,
    [Category(IndicatorType.Momentum)]
    AdaptiveRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    AdaptiveStochastic,
    [Category(IndicatorType.Trend)]
    AdaptiveTrailingStop,
    [Category(IndicatorType.Trend)]
    AhrensMovingAverage,
    [Category(IndicatorType.Trend)]
    AlligatorIndex,
    [Category(IndicatorType.Trend)]
    AlphaDecreasingExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    AnchoredMomentum,
    [Category(IndicatorType.Momentum)]
    ApirineSlowRelativeStrengthIndex,
    [Category(IndicatorType.Trend)]
    ArnaudLegouxMovingAverage,
    [Category(IndicatorType.Trend)]
    AroonOscillator,
    [Category(IndicatorType.Momentum)]
    AsymmetricalRelativeStrengthIndex,
    [Category(IndicatorType.Trend)]
    AtrFilteredExponentialMovingAverage,
    [Category(IndicatorType.Volatility)]
    AutoDispersionBands,
    [Category(IndicatorType.Trend)]
    AutoFilter,
    [Category(IndicatorType.Trend)]
    AutoLine,
    [Category(IndicatorType.Trend)]
    AutoLineWithDrift,
    [Category(IndicatorType.Trend)]
    AutonomousRecursiveMovingAverage,
    [Category(IndicatorType.Momentum)]
    AverageAbsoluteErrorNormalization,
    [Category(IndicatorType.Trend)]
    AverageDirectionalIndex,
    [Category(IndicatorType.Momentum)]
    AverageMoneyFlowOscillator,
    [Category(IndicatorType.Volatility)]
    AverageTrueRange,
    [Category(IndicatorType.Volatility)]
    AverageTrueRangeChannel,
    [Category(IndicatorType.Trend)]
    AverageTrueRangeTrailingStops,
    [Category(IndicatorType.Momentum)]
    AwesomeOscillator,
    [Category(IndicatorType.Momentum)]
    BalanceOfPower,
    [Category(IndicatorType.Momentum)]
    BayesianOscillator,
    [Category(IndicatorType.Momentum)]
    BearPowerIndicator,
    [Category(IndicatorType.Momentum)]
    BelkhayateTiming,
    [Category(IndicatorType.Volume)]
    BetterVolumeIndicator,
    [Category(IndicatorType.Trend)]
    BilateralStochasticOscillator,
    [Category(IndicatorType.Volatility)]
    BollingerBands,
    [Category(IndicatorType.Volatility)]
    BollingerBandsAverageTrueRange,
    [Category(IndicatorType.Volatility)]
    BollingerBandsFibonacciRatios,
    [Category(IndicatorType.Momentum)]
    BollingerBandsPercentB,
    [Category(IndicatorType.Volatility)]
    BollingerBandsWidth,
    [Category(IndicatorType.Volatility)]
    BollingerBandsWithAtrPct,
    [Category(IndicatorType.Momentum)]
    BreakoutRelativeStrengthIndex,
    [Category(IndicatorType.Trend)]
    BryantAdaptiveMovingAverage,
    [Category(IndicatorType.Trend)]
    BuffAverage,
    [Category(IndicatorType.Momentum)]
    BullPowerIndicator,
    [Category(IndicatorType.Volatility)]
    CalmarRatio,
    [Category(IndicatorType.SupportAndResistance)]
    CamarillaPivotPoints,
    [Category(IndicatorType.Momentum)]
    CCTStochRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    CenterOfLinearity,
    [Category(IndicatorType.Volume)]
    ChaikinMoneyFlow,
    [Category(IndicatorType.Volume)]
    ChaikinOscillator,
    [Category(IndicatorType.Volatility)]
    ChaikinVolatility,
    [Category(IndicatorType.Momentum)]
    ChandeCompositeMomentumIndex,
    [Category(IndicatorType.Momentum)]
    ChandeForecastOscillator,
    [Category(IndicatorType.Momentum)]
    ChandeIntradayMomentumIndex,
    [Category(IndicatorType.Momentum)]
    ChandeKrollRSquaredIndex,
    [Category(IndicatorType.Momentum)]
    ChandeMomentumOscillator,
    [Category(IndicatorType.Momentum)]
    ChandeMomentumOscillatorAbsolute,
    [Category(IndicatorType.Momentum)]
    ChandeMomentumOscillatorAbsoluteAverage,
    [Category(IndicatorType.Momentum)]
    ChandeMomentumOscillatorAverage,
    [Category(IndicatorType.Momentum)]
    ChandeMomentumOscillatorAverageDisparityIndex,
    [Category(IndicatorType.Momentum)]
    ChandeMomentumOscillatorFilter,
    [Category(IndicatorType.Momentum)]
    ChandeQuickStick,
    [Category(IndicatorType.Trend)]
    ChandeTrendScore,
    [Category(IndicatorType.Trend)]
    ChandeVolatilityIndexDynamicAverageIndicator,
    [Category(IndicatorType.Trend)]
    ChandelierExit,
    [Category(IndicatorType.Momentum)]
    ChartmillValueIndicator,
    [Category(IndicatorType.Trend)]
    ChopZone,
    [Category(IndicatorType.Momentum)]
    ChoppinessIndex,
    [Category(IndicatorType.Volatility)]
    ClosedFormDistanceVolatility,
    [Category(IndicatorType.Momentum)]
    CommodityChannelIndex,
    [Category(IndicatorType.Volatility)]
    CommoditySelectionIndex,
    [Category(IndicatorType.Momentum)]
    ComparePriceMomentumOscillator,
    [Category(IndicatorType.Trend)]
    CompoundRatioMovingAverage,
    [Category(IndicatorType.Trend)]
    ConditionalAccumulator,
    [Category(IndicatorType.Momentum)]
    ConfluenceIndicator,
    [Category(IndicatorType.Momentum)]
    ConnorsRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    ConstanceBrownCompositeIndex,
    [Category(IndicatorType.SupportAndResistance)]
    ContractHighLow,
    [Category(IndicatorType.Momentum)]
    CoppockCurve,
    [Category(IndicatorType.Trend)]
    CoralTrendIndicator,
    [Category(IndicatorType.Trend)]
    CorrectedMovingAverage,
    [Category(IndicatorType.Trend)]
    CubedWeightedMovingAverage,
    [Category(IndicatorType.Volatility)]
    DEnvelope,
    [Category(IndicatorType.Volatility)]
    DailyAveragePriceDelta,
    [Category(IndicatorType.Trend)]
    DampedSineWaveWeightedFilter,
    [Category(IndicatorType.Volatility)]
    DampingIndex,
    [Category(IndicatorType.Momentum)]
    DecisionPointBreadthSwenlinTradingOscillator,
    [Category(IndicatorType.Momentum)]
    DecisionPointPriceMomentumOscillator,
    [Category(IndicatorType.Trend)]
    DeltaMovingAverage,
    [Category(IndicatorType.Momentum)]
    Dema2Lines,
    [Category(IndicatorType.Momentum)]
    DemandOscillator,
    [Category(IndicatorType.SupportAndResistance)]
    DemarkPivotPoints,
    [Category(IndicatorType.Momentum)]
    DemarkPressureRatioV1,
    [Category(IndicatorType.Momentum)]
    DemarkPressureRatioV2,
    [Category(IndicatorType.Momentum)]
    DemarkRangeExpansionIndex,
    [Category(IndicatorType.Trend)]
    DemarkReversalPoints,
    [Category(IndicatorType.Trend)]
    DemarkSetupIndicator,
    [Category(IndicatorType.Momentum)]
    Demarker,
    [Category(IndicatorType.Momentum)]
    DerivativeOscillator,
    [Category(IndicatorType.Momentum)]
    DetrendedPriceOscillator,
    [Category(IndicatorType.Momentum)]
    DetrendedSyntheticPrice,
    [Category(IndicatorType.Trend)]
    DidiIndex,
    [Category(IndicatorType.Momentum)]
    DiNapoliMovingAverageConvergenceDivergence,
    [Category(IndicatorType.Momentum)]
    DiNapoliPercentagePriceOscillator,
    [Category(IndicatorType.Momentum)]
    DiNapoliPreferredStochasticOscillator,
    [Category(IndicatorType.Momentum)]
    DirectionalTrendIndex,
    [Category(IndicatorType.Momentum)]
    DisparityIndex,
    [Category(IndicatorType.Trend)]
    DistanceWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    DMIStochastic,
    [Category(IndicatorType.Momentum)]
    DominantCycleTunedRelativeStrengthIndex,
    [Category(IndicatorType.Volatility)]
    DonchianChannelWidth,
    [Category(IndicatorType.SupportAndResistance)]
    DonchianChannels,
    [Category(IndicatorType.Trend)]
    DoubleExponentialMovingAverage,
    [Category(IndicatorType.Trend)]
    DoubleExponentialSmoothing,
    [Category(IndicatorType.Momentum)]
    DoubleSmoothedMomenta,
    [Category(IndicatorType.Momentum)]
    DoubleSmoothedRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    DoubleSmoothedStochastic,
    [Category(IndicatorType.Momentum)]
    DoubleStochasticOscillator,
    [Category(IndicatorType.Volatility)]
    DrunkardWalk,
    [Category(IndicatorType.Momentum)]
    DTOscillator,
    [Category(IndicatorType.Momentum)]
    DynamicMomentumIndex,
    [Category(IndicatorType.Momentum)]
    DynamicMomentumOscillator,
    [Category(IndicatorType.SupportAndResistance)]
    DynamicPivotPoints,
    [Category(IndicatorType.SupportAndResistance)]
    DynamicSupportAndResistance,
    [Category(IndicatorType.Trend)]
    DynamicallyAdjustableFilter,
    [Category(IndicatorType.Trend)]
    DynamicallyAdjustableMovingAverage,
    [Category(IndicatorType.SupportAndResistance)]
    EarningSupportResistanceLevels,
    [Category(IndicatorType.Volume)]
    EaseOfMovement,
    [Category(IndicatorType.Trend)]
    EdgePreservingFilter,
    [Category(IndicatorType.Trend)]
    EfficientAutoLine,
    [Category(IndicatorType.Trend)]
    EfficientPrice,
    [Category(IndicatorType.SupportAndResistance)]
    EfficientTrendStepChannel,
    [Category(IndicatorType.Trend)]
    Ehlers2PoleButterworthFilterV1,
    [Category(IndicatorType.Trend)]
    Ehlers2PoleButterworthFilterV2,
    [Category(IndicatorType.Trend)]
    Ehlers2PoleSuperSmootherFilterV1,
    [Category(IndicatorType.Trend)]
    Ehlers2PoleSuperSmootherFilterV2,
    [Category(IndicatorType.Trend)]
    Ehlers3PoleButterworthFilterV1,
    [Category(IndicatorType.Trend)]
    Ehlers3PoleButterworthFilterV2,
    [Category(IndicatorType.Trend)]
    Ehlers3PoleSuperSmootherFilter,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveBandPassFilter,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveCenterOfGravityOscillator,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveCommodityChannelIndexV1,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveCommodityChannelIndexV2,
    [Category(IndicatorType.Cycle)]
    EhlersAdaptiveCyberCycle,
    [Category(IndicatorType.Trend)]
    EhlersAdaptiveLaguerreFilter,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveRelativeStrengthIndexV1,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveRelativeStrengthIndexV2,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveRsiFisherTransformV1,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveRsiFisherTransformV2,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveStochasticIndicatorV1,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveStochasticIndicatorV2,
    [Category(IndicatorType.Momentum)]
    EhlersAdaptiveStochasticInverseFisherTransform,
    [Category(IndicatorType.Trend)]
    EhlersAllPassPhaseShifter,
    [Category(IndicatorType.Volatility)]
    EhlersAlternateSignalToNoiseRatio,
    [Category(IndicatorType.Volatility)]
    EhlersAMDetector,
    [Category(IndicatorType.Volatility)]
    EhlersAnticipateIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersAutoCorrelationIndicator,
    [Category(IndicatorType.Cycle)]
    EhlersAutoCorrelationPeriodogram,
    [Category(IndicatorType.Trend)]
    EhlersAutoCorrelationReversals,
    [Category(IndicatorType.Trend)]
    EhlersAverageErrorFilter,
    [Category(IndicatorType.Momentum)]
    EhlersBandPassFilterV1,
    [Category(IndicatorType.Momentum)]
    EhlersBandPassFilterV2,
    [Category(IndicatorType.Trend)]
    EhlersBetterExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    EhlersCenterofGravityOscillator,
    [Category(IndicatorType.Trend)]
    EhlersChebyshevLowPassFilter,
    [Category(IndicatorType.Trend)]
    EhlersClassicHilbertTransformer,
    [Category(IndicatorType.Cycle)]
    EhlersCombFilterSpectralEstimate,
    [Category(IndicatorType.Momentum)]
    EhlersCommodityChannelIndexInverseFisherTransform,
    [Category(IndicatorType.Momentum)]
    EhlersConvolutionIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersCorrelationAngleIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersCorrelationCycleIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersCorrelationTrendIndicator,
    [Category(IndicatorType.Cycle)]
    EhlersCyberCycle,
    [Category(IndicatorType.Cycle)]
    EhlersCycleAmplitude,
    [Category(IndicatorType.Cycle)]
    EhlersCycleBandPassFilter,
    [Category(IndicatorType.Trend)]
    EhlersDecycler,
    [Category(IndicatorType.Momentum)]
    EhlersDecyclerOscillatorV1,
    [Category(IndicatorType.Momentum)]
    EhlersDecyclerOscillatorV2,
    [Category(IndicatorType.Momentum)]
    EhlersDetrendedLeadingIndicator,
    [Category(IndicatorType.Trend)]
    EhlersDeviationScaledMovingAverage,
    [Category(IndicatorType.Trend)]
    EhlersDeviationScaledSuperSmoother,
    [Category(IndicatorType.Cycle)]
    EhlersDiscreteFourierTransform,
    [Category(IndicatorType.Cycle)]
    EhlersDiscreteFourierTransformSpectralEstimate,
    [Category(IndicatorType.Trend)]
    EhlersDistanceCoefficientFilter,
    [Category(IndicatorType.Momentum)]
    EhlersDominantCycleTunedBypassFilter,
    [Category(IndicatorType.Momentum)]
    EhlersDualDifferentiatorDominantCycle,
    [Category(IndicatorType.Momentum)]
    EhlersEarlyOnsetTrendIndicator,
    [Category(IndicatorType.Volatility)]
    EhlersEmpiricalModeDecomposition,
    [Category(IndicatorType.Volatility)]
    EhlersEnhancedSignalToNoiseRatio,
    [Category(IndicatorType.Cycle)]
    EhlersEvenBetterSineWaveIndicator,
    [Category(IndicatorType.Trend)]
    EhlersFilter,
    [Category(IndicatorType.Trend)]
    EhlersFiniteImpulseResponseFilter,
    [Category(IndicatorType.Momentum)]
    EhlersFisherTransform,
    [Category(IndicatorType.Momentum)]
    EhlersFisherizedDeviationScaledOscillator,
    [Category(IndicatorType.Momentum)]
    EhlersFMDemodulatorIndicator,
    [Category(IndicatorType.Cycle)]
    EhlersFourierSeriesAnalysis,
    [Category(IndicatorType.Trend)]
    EhlersFractalAdaptiveMovingAverage,
    [Category(IndicatorType.Trend)]
    EhlersGaussianFilter,
    [Category(IndicatorType.Trend)]
    EhlersHammingMovingAverage,
    [Category(IndicatorType.Momentum)]
    EhlersHammingWindowIndicator,
    [Category(IndicatorType.Trend)]
    EhlersHannMovingAverage,
    [Category(IndicatorType.Momentum)]
    EhlersHannWindowIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersHighPassFilterV1,
    [Category(IndicatorType.Momentum)]
    EhlersHighPassFilterV2,
    [Category(IndicatorType.Momentum)]
    EhlersHilbertOscillator,
    [Category(IndicatorType.Momentum)]
    EhlersHilbertTransformIndicator,
    [Category(IndicatorType.Trend)]
    EhlersHilbertTransformer,
    [Category(IndicatorType.Trend)]
    EhlersHilbertTransformerIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersHomodyneDominantCycle,
    [Category(IndicatorType.Momentum)]
    EhlersHpLpRoofingFilter,
    [Category(IndicatorType.Momentum)]
    EhlersHurstCoefficient,
    [Category(IndicatorType.Momentum)]
    EhlersImpulseReaction,
    [Category(IndicatorType.Momentum)]
    EhlersImpulseResponse,
    [Category(IndicatorType.Trend)]
    EhlersInfiniteImpulseResponseFilter,
    [Category(IndicatorType.Cycle)]
    EhlersInstantaneousPhaseIndicator,
    [Category(IndicatorType.Trend)]
    EhlersInstantaneousTrendlineV1,
    [Category(IndicatorType.Trend)]
    EhlersInstantaneousTrendlineV2,
    [Category(IndicatorType.Momentum)]
    EhlersInverseFisherTransform,
    [Category(IndicatorType.Trend)]
    EhlersKaufmanAdaptiveMovingAverage,
    [Category(IndicatorType.Trend)]
    EhlersLaguerreFilter,
    [Category(IndicatorType.Momentum)]
    EhlersLaguerreRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    EhlersLaguerreRelativeStrengthIndexWithSelfAdjustingAlpha,
    [Category(IndicatorType.Trend)]
    EhlersLeadingIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersMarketStateIndicator,
    [Category(IndicatorType.Trend)]
    EhlersMedianAverageAdaptiveFilter,
    [Category(IndicatorType.Momentum)]
    EhlersMesaPredictIndicatorV1,
    [Category(IndicatorType.Momentum)]
    EhlersMesaPredictIndicatorV2,
    [Category(IndicatorType.Trend)]
    EhlersModifiedOptimumEllipticFilter,
    [Category(IndicatorType.Momentum)]
    EhlersModifiedRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    EhlersModifiedStochasticIndicator,
    [Category(IndicatorType.Trend)]
    EhlersMotherOfAdaptiveMovingAverages,
    [Category(IndicatorType.Momentum)]
    EhlersMovingAverageDifferenceIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersNoiseEliminationTechnology,
    [Category(IndicatorType.Trend)]
    EhlersOptimumEllipticFilter,
    [Category(IndicatorType.Cycle)]
    EhlersPhaseAccumulationDominantCycle,
    [Category(IndicatorType.Trend)]
    EhlersPhaseCalculation,
    [Category(IndicatorType.Trend)]
    EhlersRecursiveMedianFilter,
    [Category(IndicatorType.Momentum)]
    EhlersRecursiveMedianOscillator,
    [Category(IndicatorType.Momentum)]
    EhlersReflexIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersRelativeStrengthIndexInverseFisherTransform,
    [Category(IndicatorType.Momentum)]
    EhlersRelativeVigorIndex,
    [Category(IndicatorType.Volume)]
    EhlersRestoringPullIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersReverseExponentialMovingAverageIndicatorV1,
    [Category(IndicatorType.Trend)]
    EhlersReverseExponentialMovingAverageIndicatorV2,
    [Category(IndicatorType.Momentum)]
    EhlersRocketRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    EhlersRoofingFilterV1,
    [Category(IndicatorType.Momentum)]
    EhlersRoofingFilterV2,
    [Category(IndicatorType.Momentum)]
    EhlersRoofingFilterIndicator,
    [Category(IndicatorType.Volatility)]
    EhlersSignalToNoiseRatioV1,
    [Category(IndicatorType.Volatility)]
    EhlersSignalToNoiseRatioV2,
    [Category(IndicatorType.Momentum)]
    EhlersSimpleClipIndicator,
    [Category(IndicatorType.Cycle)]
    EhlersSimpleCycleIndicator,
    [Category(IndicatorType.Trend)]
    EhlersSimpleDecycler,
    [Category(IndicatorType.Momentum)]
    EhlersSimpleDerivIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersSimpleWindowIndicator,
    [Category(IndicatorType.Cycle)]
    EhlersSineWaveIndicatorV1,
    [Category(IndicatorType.Cycle)]
    EhlersSineWaveIndicatorV2,
    [Category(IndicatorType.Momentum)]
    EhlersSmoothedAdaptiveMomentumIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersSnakeUniversalTradingFilter,
    [Category(IndicatorType.Momentum)]
    EhlersSpearmanRankIndicator,
    [Category(IndicatorType.Cycle)]
    EhlersSpectrumDerivedFilterBank,
    [Category(IndicatorType.Cycle)]
    EhlersSquelchIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersStochastic,
    [Category(IndicatorType.Momentum)]
    EhlersStochasticCenterOfGravityOscillator,
    [Category(IndicatorType.Cycle)]
    EhlersStochasticCyberCycle,
    [Category(IndicatorType.Volatility)]
    EhlersSuperPassbandFilter,
    [Category(IndicatorType.Trend)]
    EhlersSuperSmootherFilter,
    [Category(IndicatorType.Trend)]
    EhlersSwissArmyKnifeIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersTrendExtraction,
    [Category(IndicatorType.Momentum)]
    EhlersTrendflexIndicator,
    [Category(IndicatorType.Trend)]
    EhlersTriangleMovingAverage,
    [Category(IndicatorType.Momentum)]
    EhlersTriangleWindowIndicator,
    [Category(IndicatorType.Momentum)]
    EhlersTripleDelayLineDetrender,
    [Category(IndicatorType.Momentum)]
    EhlersTruncatedBandPassFilter,
    [Category(IndicatorType.Momentum)]
    EhlersUniversalOscillator,
    [Category(IndicatorType.Momentum)]
    EhlersUniversalTradingFilter,
    [Category(IndicatorType.Trend)]
    EhlersVariableIndexDynamicAverage,
    [Category(IndicatorType.Momentum)]
    EhlersVossPredictiveFilter,
    [Category(IndicatorType.Cycle)]
    EhlersZeroCrossingsDominantCycle,
    [Category(IndicatorType.Trend)]
    EhlersZeroLagExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    EhlersZeroMeanRoofingFilter,
    [Category(IndicatorType.Trend)]
    ElasticVolumeWeightedMovingAverageV1,
    [Category(IndicatorType.Trend)]
    ElasticVolumeWeightedMovingAverageV2,
    [Category(IndicatorType.Volatility)]
    ElderMarketThermometer,
    [Category(IndicatorType.Trend)]
    ElderRayIndex,
    [Category(IndicatorType.Trend)]
    ElderSafeZoneStops,
    [Category(IndicatorType.Momentum)]
    ElliottWaveOscillator,
    [Category(IndicatorType.Momentum)]
    EmaWaveIndicator,
    [Category(IndicatorType.Trend)]
    EndPointMovingAverage,
    [Category(IndicatorType.Momentum)]
    EnhancedIndex,
    [Category(IndicatorType.Momentum)]
    EnhancedWilliamsR,
    [Category(IndicatorType.Trend)]
    EquityMovingAverage,
    [Category(IndicatorType.Momentum)]
    ErgodicCandlestickOscillator,
    [Category(IndicatorType.Volatility)]
    ErgodicCommoditySelectionIndex,
    [Category(IndicatorType.Momentum)]
    ErgodicMeanDeviationIndicator,
    [Category(IndicatorType.Momentum)]
    ErgodicMovingAverageConvergenceDivergence,
    [Category(IndicatorType.Trend)]
    ErgodicPercentagePriceOscillator,
    [Category(IndicatorType.Momentum)]
    ErgodicTrueStrengthIndexV1,
    [Category(IndicatorType.Momentum)]
    ErgodicTrueStrengthIndexV2,
    [Category(IndicatorType.Trend)]
    ExponentialMovingAverage,
    [Category(IndicatorType.Volatility)]
    ExtendedRecursiveBands,
    [Category(IndicatorType.Trend)]
    FallingRisingFilter,
    [Category(IndicatorType.Trend)]
    FareySequenceWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    FastandSlowKurtosisOscillator,
    [Category(IndicatorType.Momentum)]
    FastandSlowRelativeStrengthIndexOscillator,
    [Category(IndicatorType.Momentum)]
    FastandSlowStochasticOscillator,
    [Category(IndicatorType.Momentum)]
    FastSlowDegreeOscillator,
    [Category(IndicatorType.Momentum)]
    FastZScore,
    [Category(IndicatorType.Momentum)]
    FearAndGreedIndicator,
    [Category(IndicatorType.SupportAndResistance)]
    FibonacciPivotPoints,
    [Category(IndicatorType.SupportAndResistance)]
    FibonacciRetrace,
    [Category(IndicatorType.Trend)]
    FibonacciWeightedMovingAverage,
    [Category(IndicatorType.Volume)]
    FiniteVolumeElements,
    [Category(IndicatorType.Volatility)]
    FireflyOscillator,
    [Category(IndicatorType.Trend)]
    FisherLeastSquaresMovingAverage,
    [Category(IndicatorType.Momentum)]
    FisherTransformStochasticOscillator,
    [Category(IndicatorType.SupportAndResistance)]
    FlaggingBands,
    [Category(IndicatorType.SupportAndResistance)]
    FloorPivotPoints,
    [Category(IndicatorType.Momentum)]
    FoldedRelativeStrengthIndex,
    [Category(IndicatorType.Volume)]
    ForceIndex,
    [Category(IndicatorType.Momentum)]
    ForecastOscillator,
    [Category(IndicatorType.Volatility)]
    FractalChaosBands,
    [Category(IndicatorType.Momentum)]
    FractalChaosOscillator,
    [Category(IndicatorType.Volume)]
    FreedomOfMovement,
    [Category(IndicatorType.Trend)]
    FullTypicalPrice,
    [Category(IndicatorType.Momentum)]
    FunctionToCandles,
    [Category(IndicatorType.Momentum)]
    FXSniperIndicator,
    [Category(IndicatorType.SupportAndResistance)]
    GChannels,
    [Category(IndicatorType.Momentum)]
    GOscillator,
    [Category(IndicatorType.Momentum)]
    GainLossMovingAverage,
    [Category(IndicatorType.Trend)]
    GannHiLoActivator,
    [Category(IndicatorType.Momentum)]
    GannSwingOscillator,
    [Category(IndicatorType.Momentum)]
    GannTrendOscillator,
    [Category(IndicatorType.Volatility)]
    GarmanKlassVolatility,
    [Category(IndicatorType.Momentum)]
    GatorOscillator,
    [Category(IndicatorType.Trend)]
    GeneralFilterEstimator,
    [Category(IndicatorType.Trend)]
    GeneralizedDoubleExponentialMovingAverage,
    [Category(IndicatorType.Volatility)]
    GopalakrishnanRangeIndex,
    [Category(IndicatorType.Trend)]
    GrandTrendForecasting,
    [Category(IndicatorType.Trend)]
    GroverLlorensActivator,
    [Category(IndicatorType.Cycle)]
    GroverLlorensCycleOscillator,
    [Category(IndicatorType.Trend)]
    GuppyCountBackLine,
    [Category(IndicatorType.Trend)]
    GuppyDistanceIndicator,
    [Category(IndicatorType.Momentum)]
    GuppyMultipleMovingAverage,
    [Category(IndicatorType.Trend)]
    HalfTrend,
    [Category(IndicatorType.Trend)]
    HampelFilter,
    [Category(IndicatorType.Volume)]
    HawkeyeVolumeIndicator,
    [Category(IndicatorType.Trend)]
    HendersonWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    HerrickPayoffIndex,
    [Category(IndicatorType.SupportAndResistance)]
    HighLowBands,
    [Category(IndicatorType.Momentum)]
    HighLowIndex,
    [Category(IndicatorType.SupportAndResistance)]
    HighLowMovingAverage,
    [Category(IndicatorType.SupportAndResistance)]
    HirashimaSugitaRS,
    [Category(IndicatorType.Volatility)]
    HistoricalVolatility,
    [Category(IndicatorType.Volatility)]
    HistoricalVolatilityPercentile,
    [Category(IndicatorType.Trend)]
    HoltExponentialMovingAverage,
    [Category(IndicatorType.Trend)]
    HullEstimate,
    [Category(IndicatorType.Trend)]
    HullMovingAverage,
    [Category(IndicatorType.SupportAndResistance)]
    HurstBands,
    [Category(IndicatorType.Cycle)]
    HurstCycleChannel,
    [Category(IndicatorType.Trend)]
    HybridConvolutionFilter,
    [Category(IndicatorType.Trend)]
    IchimokuCloud,
    [Category(IndicatorType.Trend)]
    IIRLeastSquaresEstimate,
    [Category(IndicatorType.Momentum)]
    ImpulseMovingAverageConvergenceDivergence,
    [Category(IndicatorType.Momentum)]
    ImpulsePercentagePriceOscillator,
    [Category(IndicatorType.Momentum)]
    InertiaIndicator,
    [Category(IndicatorType.Volatility)]
    InformationRatio,
    [Category(IndicatorType.Trend)]
    InsyncIndex,
    [Category(IndicatorType.Momentum)]
    InternalBarStrengthIndicator,
    [Category(IndicatorType.Volatility)]
    InterquartileRangeBands,
    [Category(IndicatorType.Trend)]
    InverseDistanceWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    InverseFisherFastZScore,
    [Category(IndicatorType.Momentum)]
    InverseFisherZScore,
    [Category(IndicatorType.Momentum)]
    JapaneseCorrelationCoefficient,
    [Category(IndicatorType.Momentum)]
    JmaRsxClone,
    [Category(IndicatorType.Volatility)]
    JrcFractalDimension,
    [Category(IndicatorType.Trend)]
    JsaMovingAverage,
    [Category(IndicatorType.Trend)]
    JurikMovingAverage,
    [Category(IndicatorType.Trend)]
    KalmanSmoother,
    [Category(IndicatorType.Momentum)]
    KarobeinOscillator,
    [Category(IndicatorType.Momentum)]
    KaseConvergenceDivergence,
    [Category(IndicatorType.SupportAndResistance)]
    KaseDevStopV1,
    [Category(IndicatorType.SupportAndResistance)]
    KaseDevStopV2,
    [Category(IndicatorType.Volume)]
    KaseIndicator,
    [Category(IndicatorType.Momentum)]
    KasePeakOscillatorV1,
    [Category(IndicatorType.Momentum)]
    KasePeakOscillatorV2,
    [Category(IndicatorType.Volatility)]
    KaseSerialDependencyIndex,
    [Category(IndicatorType.Volatility)]
    KaufmanAdaptiveBands,
    [Category(IndicatorType.Momentum)]
    KaufmanAdaptiveCorrelationOscillator,
    [Category(IndicatorType.Trend)]
    KaufmanAdaptiveLeastSquaresMovingAverage,
    [Category(IndicatorType.Trend)]
    KaufmanAdaptiveMovingAverage,
    [Category(IndicatorType.Momentum)]
    KaufmanBinaryWave,
    [Category(IndicatorType.Momentum)]
    KaufmanStressIndicator,
    [Category(IndicatorType.Volatility)]
    KeltnerChannels,
    [Category(IndicatorType.Volatility)]
    KendallRankCorrelationCoefficient,
    [Category(IndicatorType.Volatility)]
    KirshenbaumBands,
    [Category(IndicatorType.Volume)]
    KlingerVolumeOscillator,
    [Category(IndicatorType.Momentum)]
    KnowSureThing,
    [Category(IndicatorType.Momentum)]
    KurtosisIndicator,
    [Category(IndicatorType.Momentum)]
    KwanIndicator,
    [Category(IndicatorType.SupportAndResistance)]
    LBRPaintBars,
    [Category(IndicatorType.Trend)]
    LeastSquaresMovingAverage,
    [Category(IndicatorType.Trend)]
    LeoMovingAverage,
    [Category(IndicatorType.Trend)]
    LightLeastSquaresMovingAverage,
    [Category(IndicatorType.Momentum)]
    LindaRaschke3_10Oscillator,
    [Category(IndicatorType.SupportAndResistance)]
    LinearChannels,
    [Category(IndicatorType.Trend)]
    LinearExtrapolation,
    [Category(IndicatorType.Momentum)]
    LinearQuadraticConvergenceDivergenceOscillator,
    [Category(IndicatorType.Trend)]
    LinearRegression,
    [Category(IndicatorType.Trend)]
    LinearRegressionLine,
    [Category(IndicatorType.Trend)]
    LinearTrailingStop,
    [Category(IndicatorType.Trend)]
    LinearWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    LiquidRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    LogisticCorrelation,
    [Category(IndicatorType.Momentum)]
    MacZIndicator,
    [Category(IndicatorType.Volume)]
    MacZVwapIndicator,
    [Category(IndicatorType.Momentum)]
    MarketDirectionIndicator,
    [Category(IndicatorType.Volume)]
    MarketFacilitationIndex,
    [Category(IndicatorType.Volatility)]
    MartinRatio,
    [Category(IndicatorType.Momentum)]
    MassIndex,
    [Category(IndicatorType.Trend)]
    MassThrustIndicator,
    [Category(IndicatorType.Momentum)]
    MassThrustOscillator,
    [Category(IndicatorType.Volatility)]
    MayerMultiple,
    [Category(IndicatorType.Momentum)]
    McClellanOscillator,
    [Category(IndicatorType.Trend)]
    McGinleyDynamicIndicator,
    [Category(IndicatorType.Trend)]
    McNichollMovingAverage,
    [Category(IndicatorType.Volatility)]
    MeanAbsoluteDeviationBands,
    [Category(IndicatorType.Volatility)]
    MeanAbsoluteErrorBands,
    [Category(IndicatorType.Trend)]
    MedianPrice,
    [Category(IndicatorType.Trend)]
    MiddleHighLowMovingAverage,
    [Category(IndicatorType.Trend)]
    Midpoint,
    [Category(IndicatorType.Momentum)]
    MidpointOscillator,
    [Category(IndicatorType.Trend)]
    Midprice,
    [Category(IndicatorType.Momentum)]
    MirroredMovingAverageConvergenceDivergence,
    [Category(IndicatorType.Momentum)]
    MirroredPercentagePriceOscillator,
    [Category(IndicatorType.Momentum)]
    MobilityOscillator,
    [Category(IndicatorType.Trend)]
    ModifiedGannHiloActivator,
    [Category(IndicatorType.Volume)]
    ModifiedPriceVolumeTrend,
    [Category(IndicatorType.Trend)]
    ModularFilter,
    [Category(IndicatorType.Momentum)]
    MomentaRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    MomentumOscillator,
    [Category(IndicatorType.Volume)]
    MoneyFlowIndex,
    [Category(IndicatorType.Momentum)]
    MorphedSineWave,
    [Category(IndicatorType.Volatility)]
    MotionSmoothnessIndex,
    [Category(IndicatorType.SupportAndResistance)]
    MotionToAttractionChannels,
    [Category(IndicatorType.Trend)]
    MotionToAttractionTrailingStop,
    [Category(IndicatorType.Momentum)]
    MoveTracker,
    [Category(IndicatorType.Volatility)]
    MovingAverageAdaptiveFilter,
    [Category(IndicatorType.Trend)]
    MovingAverageAdaptiveQ,
    [Category(IndicatorType.Volatility)]
    MovingAverageBandWidth,
    [Category(IndicatorType.Volatility)]
    MovingAverageBands,
    [Category(IndicatorType.SupportAndResistance)]
    MovingAverageChannel,
    [Category(IndicatorType.Momentum)]
    MovingAverageConvergenceDivergence,
    [Category(IndicatorType.Momentum)]
    MovingAverageConvergenceDivergenceLeader,
    [Category(IndicatorType.SupportAndResistance)]
    MovingAverageDisplacedEnvelope,
    [Category(IndicatorType.SupportAndResistance)]
    MovingAverageEnvelope,
    [Category(IndicatorType.SupportAndResistance)]
    MovingAverageSupportResistance,
    [Category(IndicatorType.Trend)]
    MovingAverageV3,
    [Category(IndicatorType.Trend)]
    MultiDepthZeroLagExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    MultiLevelIndicator,
    [Category(IndicatorType.Volume)]
    MultiVoteOnBalanceVolume,
    [Category(IndicatorType.Momentum)]
    NarrowBandpassFilter,
    [Category(IndicatorType.Volatility)]
    NarrowSidewaysChannel,
    [Category(IndicatorType.Momentum)]
    NaturalDirectionalCombo,
    [Category(IndicatorType.Momentum)]
    NaturalDirectionalIndex,
    [Category(IndicatorType.Momentum)]
    NaturalMarketCombo,
    [Category(IndicatorType.Momentum)]
    NaturalMarketMirror,
    [Category(IndicatorType.Momentum)]
    NaturalMarketRiver,
    [Category(IndicatorType.Momentum)]
    NaturalMarketSlope,
    [Category(IndicatorType.Trend)]
    NaturalMovingAverage,
    [Category(IndicatorType.Momentum)]
    NaturalStochasticIndicator,
    [Category(IndicatorType.Volume)]
    NegativeVolumeDisparityIndicator,
    [Category(IndicatorType.Volume)]
    NegativeVolumeIndex,
    [Category(IndicatorType.Trend)]
    NickRypockTrailingReverse,
    [Category(IndicatorType.Momentum)]
    NormalizedRelativeVigorIndex,
    [Category(IndicatorType.Momentum)]
    NthOrderDifferencingOscillator,
    [Category(IndicatorType.Momentum)]
    OCHistogram,
    [Category(IndicatorType.Momentum)]
    OceanIndicator,
    [Category(IndicatorType.Volatility)]
    OmegaRatio,
    [Category(IndicatorType.Volume)]
    OnBalanceVolume,
    [Category(IndicatorType.Volume)]
    OnBalanceVolumeDisparityIndicator,
    [Category(IndicatorType.Volume)]
    OnBalanceVolumeModified,
    [Category(IndicatorType.Volume)]
    OnBalanceVolumeReflex,
    [Category(IndicatorType.Trend)]
    OptimalWeightedMovingAverage,
    [Category(IndicatorType.Trend)]
    OptimizedTrendTracker,
    [Category(IndicatorType.Momentum)]
    OscOscillator,
    [Category(IndicatorType.Momentum)]
    OscarIndicator,
    [Category(IndicatorType.Trend)]
    OvershootReductionMovingAverage,
    [Category(IndicatorType.Trend)]
    ParabolicSAR,
    [Category(IndicatorType.Trend)]
    ParabolicWeightedMovingAverage,
    [Category(IndicatorType.Trend)]
    ParametricCorrectiveLinearMovingAverage,
    [Category(IndicatorType.Trend)]
    ParametricKalmanFilter,
    [Category(IndicatorType.Trend)]
    PeakValleyEstimation,
    [Category(IndicatorType.Trend)]
    PentupleExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    PercentChangeOscillator,
    [Category(IndicatorType.Momentum)]
    PercentagePriceOscillator,
    [Category(IndicatorType.Momentum)]
    PercentageVolumeOscillator,
    [Category(IndicatorType.Momentum)]
    PercentagePriceOscillatorLeader,
    [Category(IndicatorType.SupportAndResistance)]
    PercentageTrailingStops,
    [Category(IndicatorType.Trend)]
    PercentageTrend,
    [Category(IndicatorType.Momentum)]
    PerformanceIndex,
    [Category(IndicatorType.SupportAndResistance)]
    PeriodicChannel,
    [Category(IndicatorType.Momentum)]
    PhaseChangeIndex,
    [Category(IndicatorType.Momentum)]
    PivotDetectorOscillator,
    [Category(IndicatorType.Trend)]
    PivotPointAverage,
    [Category(IndicatorType.Momentum)]
    PolarizedFractalEfficiency,
    [Category(IndicatorType.Trend)]
    PolynomialLeastSquaresMovingAverage,
    [Category(IndicatorType.Volume)]
    PositiveVolumeIndex,
    [Category(IndicatorType.Trend)]
    PoweredKaufmanAdaptiveMovingAverage,
    [Category(IndicatorType.Momentum)]
    PremierStochasticOscillator,
    [Category(IndicatorType.Momentum)]
    PrettyGoodOscillator,
    [Category(IndicatorType.SupportAndResistance)]
    PriceChannel,
    [Category(IndicatorType.Volatility)]
    PriceCurveChannel,
    [Category(IndicatorType.Momentum)]
    PriceCycleOscillator,
    [Category(IndicatorType.Volatility)]
    PriceHeadleyAccelerationBands,
    [Category(IndicatorType.Volatility)]
    PriceLineChannel,
    [Category(IndicatorType.Momentum)]
    PriceMomentumOscillator,
    [Category(IndicatorType.Volume)]
    PriceVolumeOscillator,
    [Category(IndicatorType.Volume)]
    PriceVolumeRank,
    [Category(IndicatorType.Volume)]
    PriceVolumeTrend,
    [Category(IndicatorType.Momentum)]
    PriceZoneOscillator,
    [Category(IndicatorType.Volatility)]
    PrimeNumberBands,
    [Category(IndicatorType.Momentum)]
    PrimeNumberOscillator,
    [Category(IndicatorType.Momentum)]
    PringSpecialK,
    [Category(IndicatorType.SupportAndResistance)]
    ProjectedSupportAndResistance,
    [Category(IndicatorType.SupportAndResistance)]
    ProjectionBands,
    [Category(IndicatorType.Volatility)]
    ProjectionBandwidth,
    [Category(IndicatorType.Volatility)]
    ProjectionOscillator,
    [Category(IndicatorType.Volatility)]
    PseudoPolynomialChannel,
    [Category(IndicatorType.Momentum)]
    PsychologicalLine,
    [Category(IndicatorType.Volatility)]
    QmaSmaDifference,
    [Category(IndicatorType.Trend)]
    QuadraticLeastSquaresMovingAverage,
    [Category(IndicatorType.Trend)]
    QuadraticMovingAverage,
    [Category(IndicatorType.Trend)]
    QuadraticRegression,
    [Category(IndicatorType.Trend)]
    QuadrupleExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    QuantitativeQualitativeEstimation,
    [Category(IndicatorType.Volatility)]
    QuasiWhiteNoise,
    [Category(IndicatorType.Trend)]
    QuickMovingAverage,
    [Category(IndicatorType.Trend)]
    R2AdaptiveRegression,
    [Category(IndicatorType.Momentum)]
    RahulMohindarOscillator,
    [Category(IndicatorType.Momentum)]
    RainbowOscillator,
    [Category(IndicatorType.Trend)]
    RandomWalkIndex,
    [Category(IndicatorType.Momentum)]
    RangeActionVerificationIndex,
    [Category(IndicatorType.Volatility)]
    RangeBands,
    [Category(IndicatorType.SupportAndResistance)]
    RangeIdentifier,
    [Category(IndicatorType.Momentum)]
    RapidRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    RateOfChange,
    [Category(IndicatorType.Volatility)]
    RateOfChangeBands,
    [Category(IndicatorType.Trend)]
    RatioOCHLAverager,
    [Category(IndicatorType.Momentum)]
    ReallySimpleIndicator,
    [Category(IndicatorType.Momentum)]
    RecursiveDifferenciator,
    [Category(IndicatorType.Trend)]
    RecursiveMovingTrendAverage,
    [Category(IndicatorType.Momentum)]
    RecursiveRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    RecursiveStochastic,
    [Category(IndicatorType.Momentum)]
    RegressionOscillator,
    [Category(IndicatorType.Trend)]
    RegularizedExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    RelativeDifferenceOfSquaresOscillator,
    [Category(IndicatorType.Momentum)]
    RelativeMomentumIndex,
    [Category(IndicatorType.Volatility)]
    RelativeNormalizedVolatility,
    [Category(IndicatorType.Momentum)]
    RelativeSpreadStrength,
    [Category(IndicatorType.Momentum)]
    RelativeStrength3DIndicator,
    [Category(IndicatorType.Momentum)]
    RelativeStrengthIndex,
    [Category(IndicatorType.Trend)]
    RelativeVigorIndex,
    [Category(IndicatorType.Volatility)]
    RelativeVolatilityIndexV1,
    [Category(IndicatorType.Volatility)]
    RelativeVolatilityIndexV2,
    [Category(IndicatorType.Volume)]
    RelativeVolumeIndicator,
    [Category(IndicatorType.Momentum)]
    Repulse,
    [Category(IndicatorType.Trend)]
    RepulsionMovingAverage,
    [Category(IndicatorType.Trend)]
    RetentionAccelerationFilter,
    [Category(IndicatorType.Trend)]
    RetrospectiveCandlestickChart,
    [Category(IndicatorType.Volatility)]
    ReversalPoints,
    [Category(IndicatorType.Momentum)]
    ReverseEngineeringRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    ReverseMovingAverageConvergenceDivergence,
    [Category(IndicatorType.Momentum)]
    RexOscillator,
    [Category(IndicatorType.Trend)]
    RightSidedRickerMovingAverage,
    [Category(IndicatorType.Momentum)]
    RobustWeightingOscillator,
    [Category(IndicatorType.Volatility)]
    RootMovingAverageSquaredErrorBands,
    [Category(IndicatorType.Momentum)]
    RSINGIndicator,
    [Category(IndicatorType.Momentum)]
    RSMKIndicator,
    [Category(IndicatorType.Trend)]
    RunningEquity,
    [Category(IndicatorType.Volatility)]
    ScalpersChannel,
    [Category(IndicatorType.Momentum)]
    SchaffTrendCycle,
    [Category(IndicatorType.Momentum)]
    SectorRotationModel,
    [Category(IndicatorType.Momentum)]
    SelfAdjustingRelativeStrengthIndex,
    [Category(IndicatorType.Trend)]
    SelfWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    SellGravitationIndex,
    [Category(IndicatorType.Momentum)]
    SentimentZoneOscillator,
    [Category(IndicatorType.Trend)]
    SequentiallyFilteredMovingAverage,
    [Category(IndicatorType.Trend)]
    SettingLessTrendStepFiltering,
    [Category(IndicatorType.Trend)]
    ShapeshiftingMovingAverage,
    [Category(IndicatorType.Trend)]
    SharpModifiedMovingAverage,
    [Category(IndicatorType.Volatility)]
    SharpeRatio,
    [Category(IndicatorType.Trend)]
    ShinoharaIntensityRatio,
    [Category(IndicatorType.Volatility)]
    SigmaSpikes,
    [Category(IndicatorType.Cycle)]
    SimpleCycle,
    [Category(IndicatorType.Trend)]
    SimpleLines,
    [Category(IndicatorType.Trend)]
    SimpleMovingAverage,
    [Category(IndicatorType.Trend)]
    SimplifiedLeastSquaresMovingAverage,
    [Category(IndicatorType.Trend)]
    SimplifiedWeightedMovingAverage,
    [Category(IndicatorType.Trend)]
    SineWeightedMovingAverage,
    [Category(IndicatorType.Trend)]
    SlowSmoothedMovingAverage,
    [Category(IndicatorType.SupportAndResistance)]
    SmartEnvelope,
    [Category(IndicatorType.Momentum)]
    SMIErgodicIndicator,
    [Category(IndicatorType.Momentum)]
    SmoothedDeltaRatioOscillator,
    [Category(IndicatorType.Momentum)]
    SmoothedRateOfChange,
    [Category(IndicatorType.Volatility)]
    SmoothedVolatilityBands,
    [Category(IndicatorType.Momentum)]
    SmoothedWilliamsAccumulationDistribution,
    [Category(IndicatorType.Volatility)]
    SortinoRatio,
    [Category(IndicatorType.Momentum)]
    SpearmanIndicator,
    [Category(IndicatorType.Trend)]
    Spencer15PointMovingAverage,
    [Category(IndicatorType.Trend)]
    Spencer21PointMovingAverage,
    [Category(IndicatorType.Trend)]
    SquareRootWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    SqueezeMomentumIndicator,
    [Category(IndicatorType.Volatility)]
    StandardDeviation,
    [Category(IndicatorType.Trend)]
    StandardDeviationChannel,
    [Category(IndicatorType.Volatility)]
    StandardDeviationVolatility,
    [Category(IndicatorType.SupportAndResistance)]
    StandardPivotPoints,
    [Category(IndicatorType.Trend)]
    StationaryExtrapolatedLevels,
    [Category(IndicatorType.Momentum)]
    StationaryExtrapolatedLevelsOscillator,
    [Category(IndicatorType.Volatility)]
    StatisticalVolatility,
    [Category(IndicatorType.Volatility)]
    StiffnessIndicator,
    [Category(IndicatorType.Momentum)]
    StochasticConnorsRelativeStrengthIndex,
    [Category(IndicatorType.Momentum)]
    StochasticCustomOscillator,
    [Category(IndicatorType.Momentum)]
    StochasticFastOscillator,
    [Category(IndicatorType.Momentum)]
    StochasticMomentumIndex,
    [Category(IndicatorType.Momentum)]
    StochasticMovingAverageConvergenceDivergenceOscillator,
    [Category(IndicatorType.Momentum)]
    StochasticOscillator,
    [Category(IndicatorType.Momentum)]
    StochasticRegular,
    [Category(IndicatorType.Momentum)]
    StochasticRelativeStrengthIndex,
    [Category(IndicatorType.Volatility)]
    StollerAverageRangeChannels,
    [Category(IndicatorType.Momentum)]
    StrengthOfMovement,
    [Category(IndicatorType.Trend)]
    SuperTrend,
    [Category(IndicatorType.Trend)]
    SuperTrendFilter,
    [Category(IndicatorType.SupportAndResistance)]
    SupportAndResistanceOscillator,
    [Category(IndicatorType.SupportAndResistance)]
    SupportResistance,
    [Category(IndicatorType.Trend)]
    SurfaceRoughnessEstimator,
    [Category(IndicatorType.Trend)]
    Svama,
    [Category(IndicatorType.Momentum)]
    SwamiStochastics,
    [Category(IndicatorType.Trend)]
    SymmetricallyWeightedMovingAverage,
    [Category(IndicatorType.Trend)]
    TStepLeastSquaresMovingAverage,
    [Category(IndicatorType.Trend)]
    TechnicalRank,
    [Category(IndicatorType.Trend)]
    TechnicalRatings,
    [Category(IndicatorType.Momentum)]
    TFSMboIndicator,
    [Category(IndicatorType.Momentum)]
    TFSMboPercentagePriceOscillator,
    [Category(IndicatorType.Trend)]
    TFSTetherLineIndicator,
    [Category(IndicatorType.Volume)]
    TFSVolumeOscillator,
    [Category(IndicatorType.Momentum)]
    TheRangeIndicator,
    [Category(IndicatorType.Momentum)]
    TickLineMomentumOscillator,
    [Category(IndicatorType.Trend)]
    TillsonIE2,
    [Category(IndicatorType.Trend)]
    TillsonT3MovingAverage,
    [Category(IndicatorType.SupportAndResistance)]
    TimeAndMoneyChannel,
    [Category(IndicatorType.Trend)]
    TimePriceIndicator,
    [Category(IndicatorType.SupportAndResistance)]
    TimeSeriesForecast,
    [Category(IndicatorType.SupportAndResistance)]
    TironeLevels,
    [Category(IndicatorType.Trend)]
    TopsAndBottomsFinder,
    [Category(IndicatorType.Trend)]
    TotalPowerIndicator,
    [Category(IndicatorType.Volume)]
    TradeVolumeIndex,
    [Category(IndicatorType.Trend)]
    TraderPressureIndex,
    [Category(IndicatorType.Volatility)]
    TradersDynamicIndex,
    [Category(IndicatorType.Momentum)]
    TradingMadeMoreSimplerOscillator,
    [Category(IndicatorType.Trend)]
    TrendAnalysisIndex,
    [Category(IndicatorType.Trend)]
    TrendAnalysisIndicator,
    [Category(IndicatorType.Trend)]
    TrendContinuationFactor,
    [Category(IndicatorType.Trend)]
    TrendDetectionIndex,
    [Category(IndicatorType.Trend)]
    TrendDirectionForceIndex,
    [Category(IndicatorType.Trend)]
    TrendExhaustionIndicator,
    [Category(IndicatorType.Trend)]
    TrendForceHistogram,
    [Category(IndicatorType.Trend)]
    TrendImpulseFilter,
    [Category(IndicatorType.Trend)]
    TrendIntensityIndex,
    [Category(IndicatorType.Trend)]
    TrendPersistenceRate,
    [Category(IndicatorType.Trend)]
    TrendStep,
    [Category(IndicatorType.Volatility)]
    TrendTraderBands,
    [Category(IndicatorType.Momentum)]
    TrendTriggerFactor,
    [Category(IndicatorType.Trend)]
    Trender,
    [Category(IndicatorType.Volatility)]
    TreynorRatio,
    [Category(IndicatorType.Trend)]
    TriangularMovingAverage,
    [Category(IndicatorType.Momentum)]
    TrigonometricOscillator,
    [Category(IndicatorType.Trend)]
    Trimean,
    [Category(IndicatorType.Trend)]
    TripleExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    Trix,
    [Category(IndicatorType.Momentum)]
    TrueStrengthIndex,
    [Category(IndicatorType.Trend)]
    TTMScalperIndicator,
    [Category(IndicatorType.Momentum)]
    TurboScaler,
    [Category(IndicatorType.Momentum)]
    TurboStochasticsFast,
    [Category(IndicatorType.Momentum)]
    TurboStochasticsSlow,
    [Category(IndicatorType.Trend)]
    TurboTrigger,
    [Category(IndicatorType.Volume)]
    TwiggsMoneyFlow,
    [Category(IndicatorType.Trend)]
    TypicalPrice,
    [Category(IndicatorType.Trend)]
    UberTrendIndicator,
    [Category(IndicatorType.Momentum)]
    UhlMaCrossoverSystem,
    [Category(IndicatorType.Volatility)]
    UlcerIndex,
    [Category(IndicatorType.Momentum)]
    UltimateMomentumIndicator,
    [Category(IndicatorType.Trend)]
    UltimateMovingAverage,
    [Category(IndicatorType.Volatility)]
    UltimateMovingAverageBands,
    [Category(IndicatorType.Momentum)]
    UltimateOscillator,
    [Category(IndicatorType.Momentum)]
    UltimateTraderOscillator,
    [Category(IndicatorType.Volatility)]
    UltimateVolatilityIndicator,
    [Category(IndicatorType.SupportAndResistance)]
    UniChannel,
    [Category(IndicatorType.Volume)]
    UpsideDownsideVolume,
    [Category(IndicatorType.Volatility)]
    UpsidePotentialRatio,
    [Category(IndicatorType.Momentum)]
    ValueChartIndicator,
    [Category(IndicatorType.Trend)]
    VanillaABCDPattern,
    [Category(IndicatorType.Momentum)]
    VaradiOscillator,
    [Category(IndicatorType.Trend)]
    VariableAdaptiveMovingAverage,
    [Category(IndicatorType.Trend)]
    VariableIndexDynamicAverage,
    [Category(IndicatorType.Trend)]
    VariableLengthMovingAverage,
    [Category(IndicatorType.Trend)]
    VariableMovingAverage,
    [Category(IndicatorType.Volatility)]
    VariableMovingAverageBands,
    [Category(IndicatorType.Volatility)]
    VerticalHorizontalFilter,
    [Category(IndicatorType.Trend)]
    VerticalHorizontalMovingAverage,
    [Category(IndicatorType.Momentum)]
    VervoortHeikenAshiCandlestickOscillator,
    [Category(IndicatorType.Momentum)]
    VervoortHeikenAshiLongTermCandlestickOscillator,
    [Category(IndicatorType.Volatility)]
    VervoortModifiedBollingerBandIndicator,
    [Category(IndicatorType.Momentum)]
    VervoortSmoothedOscillator,
    [Category(IndicatorType.Volatility)]
    VervoortVolatilityBands,
    [Category(IndicatorType.Volatility)]
    VixTradingSystem,
    [Category(IndicatorType.Volatility)]
    VolatilityBasedMomentum,
    [Category(IndicatorType.Trend)]
    VolatilityIndexDynamicAverageIndicator,
    [Category(IndicatorType.Trend)]
    VolatilityMovingAverage,
    [Category(IndicatorType.Volatility)]
    VolatilityQualityIndex,
    [Category(IndicatorType.Volatility)]
    VolatilityRatio,
    [Category(IndicatorType.Volatility)]
    VolatilitySwitchIndicator,
    [Category(IndicatorType.Trend)]
    VolatilityWaveMovingAverage,
    [Category(IndicatorType.Volume)]
    VolumeAccumulationOscillator,
    [Category(IndicatorType.Volume)]
    VolumeAccumulationPercent,
    [Category(IndicatorType.Volume)]
    VolumeAdaptiveBands,
    [Category(IndicatorType.Trend)]
    VolumeAdjustedMovingAverage,
    [Category(IndicatorType.Volume)]
    VolumeFlowIndicator,
    [Category(IndicatorType.Volume)]
    VolumePositiveNegativeIndicator,
    [Category(IndicatorType.Volume)]
    VolumePriceConfirmationIndicator,
    [Category(IndicatorType.Trend)]
    VolumeWeightedAveragePrice,
    [Category(IndicatorType.Trend)]
    VolumeWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    VolumeWeightedRelativeStrengthIndex,
    [Category(IndicatorType.Trend)]
    VortexBands,
    [Category(IndicatorType.Trend)]
    VortexIndicator,
    [Category(IndicatorType.Momentum)]
    VostroIndicator,
    [Category(IndicatorType.Trend)]
    WaddahAttarExplosion,
    [Category(IndicatorType.Momentum)]
    WamiOscillator,
    [Category(IndicatorType.Momentum)]
    WaveTrendOscillator,
    [Category(IndicatorType.Trend)]
    WeightedClose,
    [Category(IndicatorType.Trend)]
    WeightedMovingAverage,
    [Category(IndicatorType.Trend)]
    WellRoundedMovingAverage,
    [Category(IndicatorType.Trend)]
    WellesWilderMovingAverage,
    [Category(IndicatorType.Trend)]
    WellesWilderSummation,
    [Category(IndicatorType.Volatility)]
    WellesWilderVolatilitySystem,
    [Category(IndicatorType.Momentum)]
    WilliamsAccumulationDistribution,
    [Category(IndicatorType.Momentum)]
    WilliamsFractals,
    [Category(IndicatorType.Momentum)]
    WilliamsR,
    [Category(IndicatorType.Momentum)]
    WilsonRelativePriceChannel,
    [Category(IndicatorType.Trend)]
    WindowedVolumeWeightedMovingAverage,
    [Category(IndicatorType.Momentum)]
    WoodieCommodityChannelIndex,
    [Category(IndicatorType.SupportAndResistance)]
    WoodiePivotPoints,
    [Category(IndicatorType.Volume)]
    ZDistanceFromVwap,
    [Category(IndicatorType.Momentum)]
    ZScore,
    [Category(IndicatorType.Trend)]
    ZeroLagExponentialMovingAverage,
    [Category(IndicatorType.Momentum)]
    ZeroLagSmoothedCycle,
    [Category(IndicatorType.Trend)]
    ZeroLagTripleExponentialMovingAverage,
    [Category(IndicatorType.Trend)]
    ZeroLowLagMovingAverage,
    [Category(IndicatorType.Momentum)]
    ZweigMarketBreadthIndicator
}