namespace OoplesFinance.StockIndicators.Enums
{
    public enum MovingAvgType
    {
        _1LCLeastSquaresMovingAverage,
        _3HMA,
        AdaptiveAutonomousRecursiveMovingAverage,
        AdaptiveExponentialMovingAverage,
        AdaptiveLeastSquares,
        AdaptiveMovingAverage,
        AhrensMovingAverage,
        AlphaDecreasingExponentialMovingAverage,
        ArnaudLegouxMovingAverage,
        AtrFilteredExponentialMovingAverage,
        AutoFilter,
        AutonomousRecursiveMovingAverage,
        EndPointWeightedMovingAverage,
        ExponentialMovingAverage,
        HullMovingAverage,
        JsaMovingAverage,
        JurikMovingAverage,
        KaufmanAdaptiveMovingAverage,
        LeastSquaresMovingAverage,
        LinearRegression,
        MesaAdaptiveMovingAverage,
        PoweredKaufmanAdaptiveMovingAverage,
        SimpleMovingAverage,
        T3MovingAverage,
        TriangularMovingAverage,
        TripleExponentialMovingAverage,
        UltimateMovingAverage,
        VariableLengthMovingAverage,
        VolumeWeightedAveragePrice,
        VolumeWeightedMovingAverage,
        WeightedMovingAverage,
        WildersSmoothingMethod
    }
}

