<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestData\MovingAvg\**" />
    <EmbeddedResource Remove="TestData\MovingAvg\**" />
    <None Remove="TestData\MovingAvg\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FluentAssertions" Version="8.11.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\src\OoplesFinance.StockIndicators.csproj" />
    <ProjectReference Include="..\examples\OoplesFinance.StockIndicators.FXMacroData\OoplesFinance.StockIndicators.FXMacroData.csproj" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.85" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestData\BollingerBands\" />
    <Folder Include="TestData\Chande\" />
    <Folder Include="TestData\Demark\" />
    <Folder Include="TestData\Ehlers\" />
    <Folder Include="TestData\Inputs\" />
    <Folder Include="TestData\Macd\" />
    <Folder Include="TestData\Momentum\" />
    <Folder Include="TestData\Wilder\" />
    <Folder Include="TestData\Volume\" />
    <Folder Include="TestData\Volatility\" />
    <Folder Include="TestData\Trend\" />
    <Folder Include="TestData\TrailingStop\" />
    <Folder Include="TestData\Stochastic\" />
    <Folder Include="TestData\Rsi\" />
    <Folder Include="TestData\Ratio\" />
    <Folder Include="TestData\PriceChannel\" />
    <Folder Include="TestData\Ppo\" />
    <Folder Include="TestData\PivotPoint\" />
    <Folder Include="TestData\Oscillator\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\AAPL.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData\MovingAverage\Sma.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData\SP500.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
